name: Build project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    buildForAllSupportedPlatforms:
        name: Build for ${{ matrix.targetPlatform }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                targetPlatform:
                    - StandaloneWindows64 # Build a Windows 64-bit standalone.
                    - WebGL
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  lfs: true
            - uses: actions/cache@v2
              with:
                  path: Library
                  key: Library-${{ matrix.targetPlatform }}
                  restore-keys: Library-
            - uses: game-ci/unity-builder@v2
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
              with:
                  targetPlatform: ${{ matrix.targetPlatform }}
            - uses: actions/upload-artifact@v2
              with:
                  name: Build-${{ matrix.targetPlatform }}
                  path: build/${{ matrix.targetPlatform }}
    deployToGitHubPages:
        name: Deploy to the Web via GitHub Pages
        runs-on: ubuntu-latest
        needs: buildForAllSupportedPlatforms
        if: ${{ !cancelled() }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Download WebGL Artifact
              uses: actions/download-artifact@v3
            - name: Copy the WebGL build artifacts to the GitHub Pages directory
              env:
                  WEBGL_BUILD_PATH: ${{ format('/build/WebGL', github.workspace) }}
                  WEBGL_PAGES_PATH: ${{ format('/docs/WebGL', github.workspace) }}
              run: find $WEBGL_BUILD_PATH -type f -name "**WebGL.*" -exec cp {} $WEBGL_PAGES_PATH \;
            - name: Deploy to GitHub Pages
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  branch: main
                  file_pattern: docs/**
                  commit_message: Deploy to GitHub Pages